name: EcoFlow
main: de.amshaegar.economy.EcoFlow
author: AmShaegar
website: http://wrenchbox.de
version: 1.0
description: Economy Plugin.
commands:
  balance:
    description: Get the current account balance.
    usage: /balance [player]
  deposit:
    description: Deposit amount on <player>'s account.
    usage: /deposit <player> <amount>
  withdraw:
    description: Withdraw amount from <player>'s account.
    usage: /withdraw <player> <amount>
  pay:
    description: Pay someone the given amount of money.
    usage: /pay <player> <amount>
permissions:
  ecoflow.admin:
    description: Allow use of balance modifying and viewing commands.
    default: op