name: EcoFlow
main: de.amshaegar.economy.EcoFlow
author: AmShaegar
website: http://wrenchbox.de
version: 1.0
description: Economy Plugin.
commands:
  test:
    description: test
    usage: /test
permissions: